### PR TITLE
Lose focus when Enter it pressed

### PR DESCRIPTION
**Pull request by nikoliazekter**

### CODE REVIEW

**Comment by kotcrab** [comment]
Why do you think that NumberSelector should lose focus after pressing enter? Imho it shouldn't.

**Comment by nikoliazekter** [comment]
I'm working on a game where VisUI is used for in-game editor. If NumberSelectors/VisTextFields don't lose their focus, I can't get any game input. To lose focus in these cases I have to press some button or checkbox and that's not the way it should work. So I always have to add one extra input listener that loses actor's focus on Enter to every textfield and NumberSelector.

**Comment by intrigus** [comment]
What's wrong with extending NumberSelector?

**Comment by kotcrab** [comment]
Yep, extending is the way to go here. Sorry, but this won't get merged. I don't think this should be default behavior for NumberSelector.

**Pull request closed without merging**
