### PR TITLE
Convert projects to gradle. (WIP)

### PR DESCRIPTION
**Pull request by Favorlock**
I've converted the projects to gradle and they all compile and a distribution zip file will be created in build/distributions folder, but I haven't sorted out all issues yet and of course there are most certainly some things that haven't been added and some things could probably be achieved in a better manner.

Please feel free to leave a comment if you see anything that needs to be added and I'll work on adding those changes.

### CODE REVIEW

**Comment by Favorlock** [comment]
One issue that I'm currently having is with the spine-notifier plugin. This is the error the editor is producing: http://pastebin.com/ASY2vZJF

**Comment by Favorlock** [comment]
Ok, so I fixed the issue with the spine-notifier plugin causing the editor to crash. It was because the editor was only catching IOException when loading the plugin license. I made a couple changes for safer loading of the license.

- Check if the licenseFile string is empty
- Catch Exception instead of IOException

**Comment by Favorlock** [comment]
I have no way to test the archive deployment to nexus since I don't have one, perhaps you can test that out @kotcrab ?

**Comment by kotcrab** [comment]
Wow, this is great, thanks a lot for doing this. There is one problem before I can review: you have renamed folders to lowercase which is OK but it bumped up edited file count to over 2000. I would like to avoid that in PR so I have created `gradle` branch and renamed those folders names to lowercase. Would be great if you could recreate this PR to merge into `gradle` branch. Hope you can understand this, thanks again.

**Comment by Favorlock** [comment]
Will do!

**Pull request closed without merging**
