### PR TITLE
added setValue method

### PR DESCRIPTION
**Pull request by azakhary**
setValue method is needed when value of NumberSelector is supposed to be set from outside. Currently it is requierd to create new instance of NumberSelector each time value is changed from outside.

I also added check for min max range, so that if value is set from outside of acceptable range, it will be ignored.

### CODE REVIEW

**Comment by kotcrab** [comment]
Somehow I can't believe we missed that method.

I think if value is outside range it should be set to maximum (if value > max) or minimum (if value < min). Please change that and squash commits or close this PR and I will do it.

**Comment by azakhary** [comment]
Would love to do that, but I have to go out right now, and will be back a bit late today. Considering it's just few lines, it will be probably easier to close the PR. Thanks a lot! 

Cheers.

**Comment by kotcrab** [comment]
Ok, I added it and 0.7.4-SNAPSHOT should be available if you would like to use it. Thanks!

**Comment by azakhary** [comment]
Thanks a lot!

**Pull request closed without merging**
